<a href="https://colab.research.google.com/github/Atusha/Atusha/blob/main/Neural%20Network/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Introduction to Tensors
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#Create tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  0], dtype=int32)>

In [ ]:
#Check the dimensions of vector
vector.ndim

1

In [ ]:
#Create a matrix (having more than 1 dimension)
matrix = tf.constant([[10,9],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  9],
       [ 7, 10]], dtype=int32)>

In [ ]:
#Check the dimension of matrix
matrix.ndim

2

In [ ]:
from numpy import float16
#Create the matrix wih pre-defined data type. 
another_matrix = tf.constant([[10,9], [3,4],[8,9]], dtype = float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  9.],
       [ 3.,  4.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#Check the dimensions of another matrix
another_matrix.ndim

2

In [ ]:
#Create the tensors. 
tensor = tf.constant([[[10,9], [3,4]],  
                              [[8,9],[6,7]],
                              [[3,4],[9,2]]])
tensor
tensor.ndim

3

### Scalar : a single number
### Vector : a number with direction
### Matrix : a 2-dimensional array of numbers
### Tensor: an n-dimensional array of numbers(where  n can be any number, a 0-dim tensor is a scalar, a 1-dim tensor is a vector)




In [ ]:
#Creating tensors with tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's try to change one of the elements of the changeable tensor.
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
#Let'r try by using assign()
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [ ]:
#Let's try to change any element in unchangeable tensor. 
unchangeable_tensor[0].assign(6)

AttributeError: ignored

So, if we create tensor using varibale function , then they are changeable with the help of assign(). 
Whereas if we create using constant() , it is not changeable in any manner even without assign().

###**Creating Random Tensor**
####Random tensors are the tensors of some arbitary size which contains random numbers.



In [ ]:
#Create 2 random (but the same) tensors.
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=[3,2])
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=[3,2])
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#### Shuffle the order of the elements in the tensor.

In [ ]:
#Shuffle the tensor (valuable for when you want to to shuffle your data at the time you don't want inherent order doesn't effect learning)

nonshuffled_tensor = tf.constant([[10,7],
                                 [3,4],
                                 [5,6]])

#Shuffle the nonshuffled_tensor
tf.random.shuffle(nonshuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  6]], dtype=int32)>

#### if you want to shuffle the tensor in the same order all the time, then we have to use global as well as operation level random seed.


In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(nonshuffled_tensor, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

### Another ways to create a tensor 

In [ ]:
#Create a tensor with alll the ones. 
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Creating a tensor with all the zeros. 
tf.zeros([4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## Difference between Numpy arrays and Tensorflow tensors is:
that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
#Creating a numpy array
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

#X = tf.constant(some_matrix) #capital for matrix
#y = tf.constant(vector) #small for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Converting numpy array into tensor.
A = tf.constant(numpy_A, shape=(2,3,4)) # 2*3*4 = 24
A

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## When dealing with tensors, you probably shuld be aware of the following attributes. 

*   Shape
*   Rank
*   Axis or Dimension
*   Size

In [ ]:
#Create a tensor with 4 rank (4 dimension)

tensor_4_dim = tf.zeros(shape=(2,3,4,5))
tensor_4_dim

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_4_dim.shape, tensor_4_dim.ndim, tf.size(tensor_4_dim)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing Tensors. 

#### Tensors can be indexed just like a python lists. 


In [ ]:
# Get the first 2 elements of each dimensions. 
tensor_4_dim[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except the final one 
tensor_4_dim[:1, :1, :1,]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor (2 dimension)
tensor_2_dim = tf.zeros(shape=(2,2))
tensor_2_dim


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
#Get the last element of each dimension of the tensor. 
tensor_2_dim[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
#Add inextra dimension in rank 2 tensor. 

tensor_3_dim = tensor_2_dim[..., tf.newaxis]
tensor_3_dim

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(tensor_2_dim, axis = -1) #-1 refers to expand the final axis.

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

## Manipulating Tensors (Tensor Operation)

**Basic Operations**

In [ ]:
#You can add values to the tensor by using addition operation
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged 
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Multiplication also works
tensor * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [ ]:
#Subtraction 
tensor - 19

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -9, -12],
       [-16, -15]], dtype=int32)>

In [ ]:
#We can use tensorflow built in function too. 
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

#Matrix Multiplication

In Machine Learning, matrix multiplicatio is most used tensor operation. 

There are 2 rules our tensors (or matrices) need to fulfil if we are going to matrix multiply them : 

1. The inner dimension must match
2. The resulting matrix has the shape of the inner dimension. 


In [ ]:
#Matrix Multiplication in Tensorflow.
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix Multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Create a tensor (3,2) tensor
X = tf.constant([[1,2],[3,4],[5,6]])
#Create another (3,2) tensor
Y = tf.constant([[0,9],[8,7],[6,5]])
#Try to Matrix Multiplication of same size. 
X @ Y

InvalidArgumentError: ignored

In [ ]:
#Let's change the shape of the matrix Y
z = tf.reshape(Y, shape=(2,3))
z

In [ ]:
#Try to matrix multiply reshaped Y with X. 
X @ z

In [ ]:
#Try change the shape of X instead of Y. 
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

In [ ]:
#Transpose can do the same 
tf.transpose(X)

## The Dot Product

Matrix Multiplication is also known as dot product. 

You can perform matrix multiplications using 2 ways : 
1. tf.matmul()
2. tf.tensordot()

In [ ]:
#Perform the dot product on X & Y (requires X or Y to be transposed).
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[54, 55],
       [68, 76]], dtype=int32)>

In [ ]:
#Perform matrix multilpcation of X & Y  (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 22, 16],
       [36, 52, 38],
       [54, 82, 60]], dtype=int32)>

In [ ]:
#Perform matrix multiplication of X & Y (reshaped)
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 21, 18],
       [28, 51, 44],
       [42, 81, 70]], dtype=int32)>

### Generally when performing matrix multiplication on two tensors and of the axes doesn't line up , you will transpose (rathen than reshaping the tensor) one of the tensor to satisfy the matrix multiplication rules. 

##Changing the datatype of Tensor

Default datatype of most tensor is int32.
By default, we have 32 bit precision but we for faster and less memory usage we can use 16 bit precision. 

In [ ]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
#Create a new tensor with default datatype (int32)
C = tf.constant([7,4])
C.dtype

tf.int32

In [ ]:
#Change datatype from float32 to float16. (reduced precision - 32 bit precision tensor vs 16 bit precision tensor)
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
#Change from int32 to float32. 
E = tf.cast(C, dtype = tf.float32)
E.dtype

tf.float32

### Aggregating Tensors

Aggregating tensors means condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values. 
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation : 
1. Get the min
2. Get the max
3. Get the mean
4. Get the sum 


In [ ]:
#Creating a random Tensor with values between 0 and 100 of size 50. 
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 18, 99, 14, 98, 96, 15, 78,  7, 54, 45, 61, 50, 94, 92, 38, 53,
       87,  2, 65, 77, 96, 13, 91, 16, 45, 40, 75, 18, 46, 29, 42, 67,  8,
       41, 29, 22, 50, 70, 49, 44, 11, 12, 88, 87, 95, 45, 62, 20, 50])>

In [ ]:
#Get the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
#using numpy
np.min(E)

2

In [ ]:
#Get the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Using numpy 
np.max(E)

99

In [ ]:
#Get the mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
#Using numpy
np.mean(E)

51.96

In [ ]:
#Get the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2598>

In [ ]:
#Using numpy
np.sum(E)

2598

In [ ]:
#Get the variance of tensor, we need access to tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=894>

In [ ]:
#Get the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.88977>

Find the positional maximum and minimum of a tensor

In [ ]:
#Get the positional minimum 
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=18>

In [ ]:
#Get the positional maximum
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

## Squeezing a tensor (Removing all single dimensions)

In [ ]:
#Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensors 
It is a form of numerical encoding. 

In [ ]:
#Create a list of indices
some_list = [0,1,2,3] #Could be red, green, blue, purple

#One hot encoding our list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

### Squaring, log, Square root

In [ ]:
#Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Get the square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors & Numpy

Tensorflow interacts beautifully on numpy array

🔑 One of the main difference between Tensorflow tensor and Numpy array is that a tensor can faster on GPU or TPU (for faster numerical processing)

In [ ]:
#Create a tensor from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert out tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to numpy array 
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPUs

In [ ]:
import tensorflow as tf
#To check on which the tf is running on
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Jul 16 14:07:36 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 If you have access to a CUDA-enabled GPU, TF will automatically use it whenever possible. 
